name: Update Poll Results

on:
  push:
    branches:
      - main

jobs:
  update-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Poll Results
        run: |
          # Your script to update the poll-results.txt file goes
          echo "Results: $(date)" >> poll-results.txt
        shell: bash

      - name: Commit and Push Changes
        run: |
          git config --local user.email "ahmadbashbash99@gmail.com"
          git config --local user.name "Ahmedbashbash"
        
          git add poll-results.txt
          git commit -m "Update poll results"
          git push https://github.com/Ahmedbashbash/poll.git HEAD:main
          # Use the secret GH_TOKEN for authentication
          git push https://${{ secrets.GH_TOKEN }}@github.com/Ahmedbashbash/poll.git HEAD:main

        shell: bash
